// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZmTuB7UejW9oGNkR5-HeGNBY1a93fq9o',
    appId: '1:565573250233:web:8902c48665d3d66c72ff68',
    messagingSenderId: '565573250233',
    projectId: 'ping-5657e',
    authDomain: 'ping-5657e.firebaseapp.com',
    storageBucket: 'ping-5657e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAfaKmW87rLctyES4KOpBblruQ4lOngo',
    appId: '1:565573250233:android:018644332fe6f0c572ff68',
    messagingSenderId: '565573250233',
    projectId: 'ping-5657e',
    storageBucket: 'ping-5657e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdniBQIIZknf6G43Oq87KJqXrEDYxi7Rc',
    appId: '1:565573250233:ios:8c32c74b96979ca572ff68',
    messagingSenderId: '565573250233',
    projectId: 'ping-5657e',
    storageBucket: 'ping-5657e.firebasestorage.app',
    iosBundleId: 'com.martin.pingapp.pingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZmTuB7UejW9oGNkR5-HeGNBY1a93fq9o',
    appId: '1:565573250233:web:392ffec2e9d2d53872ff68',
    messagingSenderId: '565573250233',
    projectId: 'ping-5657e',
    authDomain: 'ping-5657e.firebaseapp.com',
    storageBucket: 'ping-5657e.firebasestorage.app',
  );

}