// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcfFrP7s861I78UTBKX6EsBCExDAOCuZ0',
    appId: '1:607056826389:web:423f1ad4674d8c5ba6be1c',
    messagingSenderId: '607056826389',
    projectId: 'pingapp-94e13',
    authDomain: 'pingapp-94e13.firebaseapp.com',
    storageBucket: 'pingapp-94e13.firebasestorage.app',
    measurementId: 'G-3FMTLXTTL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj-Ds-KrosuhllhHc78f0OlLOO94W22Dk',
    appId: '1:607056826389:android:56e1dab434cf5be2a6be1c',
    messagingSenderId: '607056826389',
    projectId: 'pingapp-94e13',
    storageBucket: 'pingapp-94e13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfx4Eh2ZVajvd9yTnTKEKGScjIpiicJY',
    appId: '1:607056826389:ios:dd486e80ca805ebaa6be1c',
    messagingSenderId: '607056826389',
    projectId: 'pingapp-94e13',
    storageBucket: 'pingapp-94e13.firebasestorage.app',
    androidClientId: '607056826389-st08hq2j8ald2eg2si8colt24mi4a5i8.apps.googleusercontent.com',
    iosClientId: '607056826389-6dugrh1bl521559ga4nljlsjnub9nqi8.apps.googleusercontent.com',
    iosBundleId: 'com.martin.pingapp.pingApp',
  );
}
