// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIAhCUfgE_eQFUJ2DX5TZ25KgNgkNNVVk',
    appId: '1:29322079000:web:cd1c9aa338e4aa0a644c6d',
    messagingSenderId: '29322079000',
    projectId: 'pingapp-17ef7',
    authDomain: 'pingapp-17ef7.firebaseapp.com',
    storageBucket: 'pingapp-17ef7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAABCNKS7zgkAX6xA_MmLkCH7LAlV6TTIY',
    appId: '1:29322079000:android:8844f77d6483ed01644c6d',
    messagingSenderId: '29322079000',
    projectId: 'pingapp-17ef7',
    storageBucket: 'pingapp-17ef7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY_1BnyowrCYPA4aN7uOYJ3OewtfKsXHQ',
    appId: '1:29322079000:ios:b631e82f6e320ac3644c6d',
    messagingSenderId: '29322079000',
    projectId: 'pingapp-17ef7',
    storageBucket: 'pingapp-17ef7.appspot.com',
    androidClientId: '29322079000-784u5q6oah9du5u8r5m60qter0a1uncu.apps.googleusercontent.com',
    iosClientId: '29322079000-5k0ir5mavjs27epo561hkup8ie1jk6qo.apps.googleusercontent.com',
    iosBundleId: 'com.martin.pingapp.pingApp',
  );

}